### ISSUE TITLE
Failure when using --since-time

### ISSUE THREAD

**Issue by dpassen** [eshelyaron/kubed#5]
When retrieving logs via the transient menu, the `--since-time` option is improperly formatted.
`transient-read-date` returns something like `2024-08-20` which I verified through the `! Command Line` option:
```sh
kubectl logs pods/ --since-time=2024-08-20 --follow --prefix --timestamps 
```
When passing the same `--since-time` on the CLI to kubectl:
```
$ kubectl version
Client Version: v1.31.0
...

$ kubectl logs pod-name -n namespace --since-time=2024-08-20
error: parsing time "2024-08-20" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "T"
```

However,
```sh
$ kubectl logs pod-name -n namespace --since-time=2024-08-20T00:00:00Z
```
works as intended.

**Comment by eshelyaron** [comment]
Hi @dpassen,

Thanks for reporting this issue!

I've pushed [a commit ](https://github.com/eshelyaron/kubed/commit/37a7fa4cfcf6beb9f2ee195ee8f7ad6e4ad58055) that should ensure we use the right format for the `--since-time` argument.
Could you please see if that solve this for you?

**Comment by dpassen** [comment]
Working great! Thanks so much for the quick turnaround (and the package, in general). :-)
