### ISSUE TITLE
Support for multiple clusters

### ISSUE THREAD

**Issue by 64J0** [eshelyaron/kubed#6]
## Summary

Does this tool has support for multiple clusters? 

With [Lens](https://k8slens.dev/), for example, we have a visual identification to let we know which cluster we're connected. I think this feature is very important, so we don't trigger commands at the wrong environment.

**Comment by eshelyaron** [comment]
Hi @64J0!

> Does this tool has support for multiple clusters?

Sure, from the [manual](https://eshelyaron.com/kubed.html#Context-and-Namespace):
"Kubed uses kubectl to interact with Kubernetes clusters, and you can use multiple kubectl contexts in Kubed to work with different Kubernetes clusters in parallel."

> With [Lens](https://k8slens.dev/), for example, we have a visual identification to let we know which cluster we're connected. I think this feature is very important, so we don't trigger commands at the wrong environment.

Yes, I agree that that's important.
In most Kubed buffers, the context is part of the buffer name, so you should see it in the mode line.
If you find this indication insufficient, please elaborate.  We can add/improve such indications if needed.

**Comment by 64J0** [comment]
Great, I'm planning to start testing this tool during this week.
