### ISSUE TITLE
Support for nodes is missing

### ISSUE THREAD

**Issue by velppa** [eshelyaron/kubed#7]
I miss support for nodes, so commands like "kubed-nodes-list" etc.  I see in the code it should be straightforward to add, so wandering if I miss something?

**Comment by eshelyaron** [comment]
Hi there, thanks for reaching out.

Indeed, adding support for another resource type is quite simple, see [Extending Kubed](https://eshelyaron.com/kubed.html#Extending-Kubed) in the manual.

We can add support for nodes out of the box as well.  What information (which columns) would you like to see about each node in the nodes list buffer?  Are there any common node-related operation you think we should support beyond listing the nodes?

**Comment by velppa** [comment]
Cool, it works! Here's my updated configuration:

```elisp
(use-package kubed :ensure t
  :config
  (kubed-define-resource node)
  (keymap-set kubed-prefix-map "n" kubed-node-prefix-map)
  :bind-keymap ("C-c k" . kubed-prefix-map))
```

Regarding standard columns, Datadog's defaults are sane:

-   Status
-   Number of pods per status
-   Age
-   CPU Usage
-   Memory Usage

I also usually group-by label "beta.kubernetes.io/instance-type" or by some custom labels, would be good to be able having column per label.

Here's the screenshot from Datadog for the reference:
<img width="1744" alt="Screenshot 2024-12-05 at 16 31 17" src="https://github.com/user-attachments/assets/23de60ef-50f3-463a-aa4b-a483d59a6504">


PS: kubed is the best Kubernetes package for Emacs! Great job!
